[package]
name = "rspirv2-tools-gen"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
tracy = ["profiling/profile-with-tracy"]

[dependencies]
rspirv2.workspace = true
clap.workspace = true
anstream.workspace = true
anyhow.workspace = true
profiling.workspace = true

[dev-dependencies]
spv.workspace = true
expect-test.workspace = true
