[workspace]
members = [
	"crates/autogen",
	"crates/grammar",
	"crates/grammar-parser",
	"crates/rspirv2",
	"crates/rspirv2-types",
	"crates/examples",
	"crates/tools",
	"crates/tools-gen",
	"spv",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["rust-gpu developers"]
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
rspirv2 = { path = "crates/rspirv2" }
rspirv2-types = { path = "crates/rspirv2-types" }
rspirv2-grammar = { path = "crates/grammar" }
rspirv2-grammar-parser = { path = "crates/grammar-parser" }
rspirv2-tools-gen = { path = "crates/tools-gen" }
spv = { path = "spv" }

anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
smallvec = { version = "1.15.1", features = ["union", "const_new", "const_generics"] }
quote = "1.0.44"
proc-macro2 = "1.0.106"
unicode-ident = "1.0.22"
convert_case = "0.10.0"
bitflags = "2.10.0"
bytemuck = "1.25.0"
prettyplease = "0.2.37"
syn = { version = "2.0.116", default-features = false }
clap = { version = "4.5.57", features = ["derive"] }
anstream = "0.6.21"
anstyle = "1.0.13"
expect-test = "1.5.1"
rustc-hash = "2.1.1"
profiling = { version = "1.0.17" }
tracy-client = { version = "0.18.4", features = ["flush-on-exit"] }

[workspace.lints.rust]
#missing_docs = "warn"
# copied from rust-gpu
future_incompatible = "warn"
nonstandard_style = "warn"
rust_2018_idioms = "warn"

[workspace.lints.clippy]
# copied from rust-gpu
all = { level = "warn", priority = -1 }
await_holding_lock = "warn"
char_lit_as_u8 = "warn"
checked_conversions = "warn"
dbg_macro = "warn"
debug_assert_with_mut_call = "warn"
doc_markdown = "warn"
empty_enums = "warn"
enum_glob_use = "warn"
#exit = "warn"
expl_impl_clone_on_copy = "warn"
explicit_deref_methods = "warn"
explicit_into_iter_loop = "warn"
fallible_impl_from = "warn"
filter_map_next = "warn"
flat_map_option = "warn"
float_cmp_const = "warn"
fn_params_excessive_bools = "warn"
from_iter_instead_of_collect = "warn"
if_let_mutex = "warn"
implicit_clone = "warn"
imprecise_flops = "warn"
inefficient_to_string = "warn"
invalid_upcast_comparisons = "warn"
large_digit_groups = "warn"
large_stack_arrays = "warn"
large_types_passed_by_value = "warn"
let_unit_value = "warn"
linkedlist = "warn"
lossy_float_literal = "warn"
macro_use_imports = "warn"
manual_ok_or = "warn"
map_flatten = "warn"
map_unwrap_or = "warn"
match_same_arms = "warn"
match_wild_err_arm = "warn"
match_wildcard_for_single_variants = "warn"
mem_forget = "warn"
missing_enforced_import_renames = "warn"
mut_mut = "warn"
mutex_integer = "warn"
needless_borrow = "warn"
needless_continue = "warn"
option_option = "warn"
path_buf_push_overwrite = "warn"
ptr_as_ptr = "warn"
rc_mutex = "warn"
ref_option_ref = "warn"
rest_pat_in_fully_bound_structs = "warn"
same_functions_in_if_condition = "warn"
semicolon_if_nothing_returned = "warn"
single_match_else = "warn"
string_add_assign = "warn"
string_add = "warn"
string_lit_as_bytes = "warn"
todo = "warn"
trait_duplication_in_bounds = "warn"
unimplemented = "warn"
unnested_or_patterns = "warn"
unused_self = "warn"
useless_transmute = "warn"
verbose_file_reads = "warn"
zero_sized_map_values = "warn"
