[workspace]
members = [
	"crates/autogen",
	"crates/grammar",
	"crates/grammar-parser",
	"crates/rspirv2",
	"crates/rspirv2-types",
	"crates/examples",
	"spv",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["rust-gpu developers"]
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
rspirv2 = { path = "crates/rspirv2" }
rspirv2-types = { path = "crates/rspirv2-types" }
rspirv2-grammar = { path = "crates/grammar" }
rspirv2-grammar-parser = { path = "crates/grammar-parser" }
spv = { path = "spv" }

anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
smallvec = { version = "1.15.1", features = ["union", "const_new", "const_generics"] }
quote = "1.0.44"
proc-macro2 = "1.0.106"
unicode-ident = "1.0.22"
convert_case = "0.10.0"
bitflags = "2.10.0"
bytemuck = "1.25.0"
prettyplease = "0.2.37"
syn = { version = "2.0.116", default-features = false }
clap = { version = "4.5.57", features = ["derive"] }
