use super::preamble::*;
pub const GRAMMAR_EXTINST: ExtInstSetGrammar = ExtInstSetGrammar {
    grammar: Grammar {
        insts: ALL_INSTS,
        operand_kinds: ALL_OPERAND_KINDS,
        inst_class: ALL_INST_CLASSES,
    },
    version: Some(100u32),
    revision: Some(2u32),
};
const ALL_INSTS: &[&InstMeta] = &[
    &ROUND,
    &ROUND_EVEN,
    &TRUNC,
    &F_ABS,
    &S_ABS,
    &F_SIGN,
    &S_SIGN,
    &FLOOR,
    &CEIL,
    &FRACT,
    &RADIANS,
    &DEGREES,
    &SIN,
    &COS,
    &TAN,
    &ASIN,
    &ACOS,
    &ATAN,
    &SINH,
    &COSH,
    &TANH,
    &ASINH,
    &ACOSH,
    &ATANH,
    &ATAN_2,
    &POW,
    &EXP,
    &LOG,
    &EXP_2,
    &LOG_2,
    &SQRT,
    &INVERSE_SQRT,
    &DETERMINANT,
    &MATRIX_INVERSE,
    &MODF,
    &MODF_STRUCT,
    &F_MIN,
    &U_MIN,
    &S_MIN,
    &F_MAX,
    &U_MAX,
    &S_MAX,
    &F_CLAMP,
    &U_CLAMP,
    &S_CLAMP,
    &F_MIX,
    &I_MIX,
    &STEP,
    &SMOOTH_STEP,
    &FMA,
    &FREXP,
    &FREXP_STRUCT,
    &LDEXP,
    &PACK_SNORM_4_X_8,
    &PACK_UNORM_4_X_8,
    &PACK_SNORM_2_X_16,
    &PACK_UNORM_2_X_16,
    &PACK_HALF_2_X_16,
    &PACK_DOUBLE_2_X_32,
    &UNPACK_SNORM_2_X_16,
    &UNPACK_UNORM_2_X_16,
    &UNPACK_HALF_2_X_16,
    &UNPACK_SNORM_4_X_8,
    &UNPACK_UNORM_4_X_8,
    &UNPACK_DOUBLE_2_X_32,
    &LENGTH,
    &DISTANCE,
    &CROSS,
    &NORMALIZE,
    &FACE_FORWARD,
    &REFLECT,
    &REFRACT,
    &FIND_I_LSB,
    &FIND_S_MSB,
    &FIND_U_MSB,
    &INTERPOLATE_AT_CENTROID,
    &INTERPOLATE_AT_SAMPLE,
    &INTERPOLATE_AT_OFFSET,
    &N_MIN,
    &N_MAX,
    &N_CLAMP,
];
const ALL_OPERAND_KINDS: &[&OperandKind] = &[];
const ALL_INST_CLASSES: &[&InstClass] = &[];
