[package]
name = "autogen"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rspirv2-codegen.workspace = true
rspirv2-grammar.workspace = true
rspirv2-grammar-parser = { workspace = true, features = ["codegen", "prettyplease"] }
anyhow.workspace = true
