[package]
name = "rspirv2"
description = "SPIR-V encoding, decoding, manipulation and disassembly"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[features]
bytemuck = ["rspirv2-types/bytemuck", "dep:bytemuck"]

[dependencies]
rspirv2-types.workspace = true
bitflags.workspace = true
smallvec.workspace = true
bytemuck = { workspace = true, optional = true }
profiling.workspace = true

[dev-dependencies]
expect-test.workspace = true
