[package]
name = "rspirv2-types"
description = "SPIR-V encoding, decoding, manipulation and disassembly"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[features]
bytemuck = ["dep:bytemuck", "bitflags/bytemuck"]

[dependencies]
# bytemuck without derive feature to not require syn and slow compilation
bytemuck = { workspace = true, optional = true }
bitflags.workspace = true
smallvec.workspace = true
anstyle.workspace = true
rustc-hash.workspace = true
profiling.workspace = true

[dev-dependencies]
anyhow.workspace = true
bytemuck = { workspace = true, features = ["extern_crate_alloc"] }
